### ISSUE TITLE
Could you provide the segmentation predictions of other compared methods?

### ISSUE THREAD

**Issue by AI-Zhpp** [ruizhechen/WaterSNet#1]
Thanks for sharing source codes. However, I find there are very different results between your paper and the original work[1][2]. The metrics are the same, but the results are very different. Could you explain this? Besides, could you provide the segmentation mask predictions of other compared methods? 

[1] MAS3K: An Open Dataset for Marine Animal Segmentation, International Symposium on Benchmarking, Measuring and Optimization 2020
[2] Marine Animal Segmentation, TCSVT2022

**Comment by scoudev** [comment]
@AI-Zhpp Thanks for your attention to our work. The results of the comparison methods in our paper are obtained by training and testing the open source code on the MAS3K dataset. You can find the code of the methods compared in our work in their oroginal paper, and conduct experiments. Please note that the work [1][2] you mentioned above didn't release their code, which is noted in our paper.

**Comment by AI-Zhpp** [comment]
Thanks for your feedback. In fact, I have already find the satement about the copied results from [1][2].However, since you have already trained and tested other compared methods, I confirm that you must get and save the predicted masks for each compared method (except [1][2]). Why not provide the predicted masks or release them for the community? I think this will help your work more convincing and can be seen by more readers. Do you think so?
